package middleware

import "net/http"

// Standard returns Forge's default HTTP middleware pipeline.
//
// The execution order is:
//
//	RequestID -> AccessLog -> Recovery -> Handler
//
// RequestID executes first so downstream middleware and handlers
// can access the request correlation ID.
//
// AccessLog wraps the recovery layer so it can record the final
// HTTP response status, including responses generated by Recovery.
//
// Recovery catches panics from downstream middleware and handlers
// and converts them into HTTP 500 responses.
func Standard(logger AccessLogger) Middleware {
	return Chain(
		RequestID,
		AccessLog(logger),
		Recovery,
	)
}

// StandardHandler applies Forge's standard middleware pipeline
// to a handler.
func StandardHandler(handler http.Handler, logger AccessLogger) http.Handler {
	return Standard(logger)(handler)
}
