package compiler

import "errors"

var (
	ErrInvalidBuildPlan          = errors.New("invalid build plan")
	ErrNilCompiler               = errors.New("compiler is nil")
	ErrNilExecutor               = errors.New("executor is nil")
	ErrNilCommandRunner          = errors.New("command runner is nil")
	ErrCommandFailed             = errors.New("command execution failed")
	ErrNilArtifactWriter         = errors.New("artifact writer is nil")
	ErrInvalidArtifact           = errors.New("invalid artifact")
	ErrInvalidOutputRoot         = errors.New("invalid artifact output root")
	ErrInvalidArtifactBundle     = errors.New("invalid artifact bundle")
	ErrInvalidArtifactPackage    = errors.New("invalid artifact package")
	ErrInvalidPackageMetadata    = errors.New("invalid package metadata")
	ErrUnsupportedPackageFormat  = errors.New("unsupported package format")
	ErrLegacyPackageUnsupported  = errors.New("legacy package unsupported")
	ErrMissingArtifactPayload    = errors.New("missing artifact payload")
	ErrInvalidPackageIntegrity   = errors.New("invalid package integrity")
	ErrIntegrityMismatch         = errors.New("package integrity mismatch")
	ErrMissingPackageIntegrity   = errors.New("missing package integrity")
	ErrInvalidPackageSignature   = errors.New("invalid package signature")
	ErrSignatureMismatch         = errors.New("package signature mismatch")
	ErrUntrustedPackageKey       = errors.New("untrusted package signing key")
	ErrNilTrustStore             = errors.New("trust store is nil")
	ErrInvalidTrustKey           = errors.New("invalid trust key")
	ErrDuplicateTrustKey         = errors.New("trust key already registered")
	ErrTrustKeyNotFound          = errors.New("trust key not found")
	ErrMissingPackageSignature   = errors.New("missing package signature")
	ErrPackageVerifierRequired   = errors.New("package verifier is required")
	ErrInvalidVerificationPolicy = errors.New("invalid package verification policy")
)
